#!bin/bash

# git
sudo apt-get install git

# Plank
sudo add-apt-repository ppa:ricotz/docky
sudo apt-get update
sudo apt-get install plank

# put plank desktop file to startup (~/.config/autostart)

# Pantheon Terminal
sudo add-apt-repository ppa:elementary-os/daily
sudo apt-get update
sudo dpkg --configure -a
sudo apt-get -f install
sudo apt-get install pantheon-terminal
sudo apt-add-repository --remove ppa:elementary-os/daily
sudo apt-get update

# Fish Shell
sudo apt-get install fish
chsh -s /usr/bin/fish

# Curl
sudo apt-get install curl

# Fisherman
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher

# Fish Simple Theme
fisher simple

# Opera Browser
sudo add-apt-repository "deb http://deb.opera.com/opera/ stable non-free"
wget -O - http://deb.opera.com/archive.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install opera-stable

# Sublime Text
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo apt-get install apt-transport-https
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
sudo apt-get install sublime-text

# Adapta theme
sudo apt-add-repository ppa:tista/adapta -y
sudo apt update  
sudo apt install adapta-gtk-theme

# Paper icon theme
sudo add-apt-repository ppa:snwh/pulp
sudo apt-get update
sudo apt-get install paper-icon-theme
sudo apt-get install paper-cursor-theme

# Papirus icon theme
sudo add-apt-repository ppa:papirus/papirus
sudo apt-get update
sudo apt-get install papirus-icon-theme

# 7z utiliy
sudo apt-get install p7zip-full

# thefuck
sudo pip3 install thefuck
