#!bin/bash

# Launcher/Shortcut creator
sudo apt-get install --no-install-recommends gnome-panel

## to run: gnome-desktop-item-edit --create-new ~/Desktop

# JQ (JSON Processor)
sudo apt-get install jq
