#!bin/bash

# Launcher/Shortcut creator
sudo apt-get install --no-install-recommends gnome-panel

## to run: gnome-desktop-item-edit --create-new ~/Desktop

# JQ (JSON Processor)
sudo apt-get install jq

# psensor
sudo apt-get install psensor

# fluxgui
sudo add-apt-repository ppa:nathan-renniewaldock/flux
sudo apt-get update
sudo apt-get install fluxgui
